### ISSUE TITLE
The CreateUserCommand is not used in the project

### ISSUE THREAD

**Issue by yigubigu** [khauser/microservices4vaadin#3]
As I review source code, there is no  place to create a new CreateUserCommand. Is this part not completed?

**Comment by khauser** [comment]
You could find `CreateUserCommand` in the `eventstore` and yes it's fully implemented. The process is initiated in the `authserver` when starting a new user registration. There first a `authserver`-user is created and afterward a REST-call to the `eventstore` is used to create the `CreateUserCommand` object which is published on the queue to be processed by a subscriber (in our case the `userservice`).
